# Generated by Django 5.0.6 on 2026-08-19 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=1000)),
                ('publication_id', models.CharField(max_length=200, unique=True)),
                ('thumbnail', models.URLField(blank=True, default='', max_length=1000)),
                ('institution', models.CharField(default='Kenya Agricultural and Livestock Research Organization', max_length=300)),
                ('author', models.JSONField(blank=True, default=list, help_text='List of author name strings')),
                ('publish_date', models.CharField(blank=True, default='', help_text='Raw value as submitted, e.g. 2018/01/08', max_length=20)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('factsheet', 'Factsheet'), ('training_manual', 'Training Manual'), ('farmer_guide', 'Farmer Guide'), ('technical_manual', 'Technical Manual'), ('qa_pair', 'Q&A Pair'), ('dataset_description', 'Dataset Description')], max_length=40)),
                ('language', models.CharField(default='en', max_length=10)),
                ('available_languages', models.JSONField(blank=True, default=list)),
                ('sector', models.CharField(choices=[('crops', 'Crops'), ('livestock', 'Livestock'), ('aquaculture', 'Aquaculture'), ('natural_resource_management', 'Natural Resource Management'), ('cross_cutting', 'Cross-Cutting')], max_length=40)),
                ('value_chain', models.CharField(db_index=True, max_length=120)),
                ('commodity', models.JSONField(blank=True, default=list)),
                ('production_system', models.JSONField(blank=True, default=list)),
                ('advisory_domain', models.JSONField(blank=True, default=list)),
                ('target_users', models.JSONField(blank=True, default=list)),
                ('geographic_applicability', models.JSONField(blank=True, default=dict, help_text='{"country": "Kenya", "counties": [...], "agro_ecological_zones": [...], "notes": ""}')),
                ('seasonality', models.JSONField(blank=True, default=dict, help_text='{"season": [...], "production_stage": [...], "timing_notes": ""}')),
                ('license', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(blank=True, choices=[('source_validated', 'Source Validated'), ('expert_reviewed', 'Expert Reviewed'), ('field_validated', 'Field Validated'), ('requires_review', 'Requires Review'), ('deprecated', 'Deprecated')], default='', max_length=30)),
                ('validated_by', models.JSONField(blank=True, default=list)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('preferred_citation', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=10)),
                ('risk_domains', models.JSONField(blank=True, default=list)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('escalation_guidance', models.TextField(blank=True, default='')),
                ('safety_disclaimer', models.TextField(blank=True, default='')),
                ('currency_status', models.CharField(blank=True, choices=[('current', 'Current'), ('needs_update', 'Needs Update'), ('outdated', 'Outdated'), ('needs_verification', 'Needs Verification')], default='', max_length=25)),
                ('scientific_accuracy_check', models.CharField(blank=True, choices=[('verified', 'Verified'), ('needs_review', 'Needs Review'), ('flagged_inaccurate', 'Flagged - Inaccurate')], default='', max_length=25)),
                ('quality_flag', models.CharField(blank=True, choices=[('ready_to_certify', 'Ready to Certify'), ('needs_review', 'Needs Review'), ('needs_update', 'Needs Update'), ('duplicate', 'Duplicate'), ('reject', 'Reject')], default='', max_length=25)),
                ('screening_notes', models.TextField(blank=True, default='')),
                ('screened_at', models.DateTimeField(blank=True, null=True)),
                ('vector_sync_status', models.CharField(choices=[('not_synced', 'Not Synced'), ('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='not_synced', max_length=15)),
                ('vector_synced_at', models.DateTimeField(blank=True, null=True)),
                ('vector_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=200, unique=True)),
                ('reading_order', models.PositiveIntegerField()),
                ('content_header', models.CharField(blank=True, default='', max_length=300)),
                ('content_text', models.TextField()),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('content_images', models.JSONField(blank=True, default=list)),
                ('content_tables', models.JSONField(blank=True, default=list)),
                ('content_warnings', models.JSONField(blank=True, default=list)),
                ('content_tags', models.JSONField(blank=True, default=list)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='advisory.advisoryresource')),
            ],
            options={
                'ordering': ['resource', 'reading_order'],
            },
        ),
        migrations.AddIndex(
            model_name='advisoryresource',
            index=models.Index(fields=['sector', 'value_chain'], name='advisory_ad_sector_bf7806_idx'),
        ),
        migrations.AddIndex(
            model_name='advisoryresource',
            index=models.Index(fields=['quality_flag'], name='advisory_ad_quality_103d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='advisoryresource',
            index=models.Index(fields=['risk_level'], name='advisory_ad_risk_le_5a3ed7_idx'),
        ),
    ]
