# Generated by Django 5.0.6 on 2026-08-19 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.SlugField(help_text="Network identity, e.g. 'kalro.kilimostack'", max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('institution_type', models.CharField(choices=[('research_institution', 'Research Institution'), ('university', 'University'), ('ngo', 'NGO'), ('cooperative_fpo', 'Cooperative / FPO'), ('financial_institution', 'Financial Institution'), ('equipment_service', 'Equipment / Mechanization Service'), ('input_supplier', 'Agro-Input Supplier'), ('market_data_provider', 'Market Data Provider'), ('aggregator', 'Aggregator / Off-taker'), ('government_agency', 'Government Agency'), ('other', 'Other')], default='other', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('website', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('schema_hint', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ProviderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reviewer', 'Reviewer'), ('admin', 'Admin')], default='reviewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='providers.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_unit', models.CharField(blank=True, default='', help_text="e.g. 'per hour', 'per 90kg bag', 'per acre'", max_length=60)),
                ('location', models.JSONField(blank=True, default=dict, help_text='{"country", "counties": [...], "agro_ecological_zones": [...]}')),
                ('availability', models.JSONField(blank=True, default=dict, help_text='Hours/days/seasonal windows this listing is offered')),
                ('fulfillment', models.JSONField(blank=True, default=dict, help_text='How to book/order: phone, method, delivery terms')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Category-specific fields -- see ServiceCategory.schema_hint')),
                ('currency_status', models.CharField(blank=True, choices=[('current', 'Current'), ('needs_update', 'Needs Update'), ('outdated', 'Outdated'), ('needs_verification', 'Needs Verification')], default='', max_length=25)),
                ('validation_status', models.CharField(blank=True, choices=[('source_validated', 'Source Validated'), ('expert_reviewed', 'Expert Reviewed'), ('field_validated', 'Field Validated'), ('requires_review', 'Requires Review'), ('deprecated', 'Deprecated')], default='', max_length=30)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=10)),
                ('quality_flag', models.CharField(blank=True, choices=[('ready_to_certify', 'Ready to Certify'), ('needs_review', 'Needs Review'), ('needs_update', 'Needs Update'), ('duplicate', 'Duplicate'), ('reject', 'Reject')], default='', max_length=25)),
                ('screening_notes', models.TextField(blank=True, default='')),
                ('screened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='providers.provider')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='providers.servicecategory')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['provider', 'category'], name='providers_c_provide_872e54_idx'), models.Index(fields=['quality_flag'], name='providers_c_quality_c9e70f_idx')],
            },
        ),
    ]
