import { Link } from "react-router-dom";
import { ArrowRight, Layers, MessageCircleQuestion, ShieldCheck, Sprout } from "lucide-react";
import { Stamp } from "@/components/Stamp";

export function Landing() {
  return (
    <div className="min-h-screen bg-canvas">
      <header className="border-b border-wire bg-paper/70 px-6 py-4 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between">
          <div>
            <p className="field-label">KilimoSTACK · OpenAgriNet</p>
            <p className="font-display text-lg font-semibold text-ink">KALRO Advisory Corpus</p>
          </div>
          <nav className="flex items-center gap-3">
            <Link to="/login" className="btn-ghost">
              Log in
            </Link>
            <Link to="/register" className="btn-primary">
              Register
            </Link>
          </nav>
        </div>
      </header>

      <section className="mx-auto max-w-6xl px-6 py-20">
        <div className="max-w-2xl">
          <div className="mb-5 flex items-center gap-2">
            <Stamp label="Reference DPI implementation" tone="herbarium" />
          </div>
          <h1 className="font-display text-5xl font-semibold leading-tight text-ink">
            Certified agricultural knowledge, ready for AI advisory.
          </h1>
          <p className="mt-5 text-lg leading-relaxed text-ink/65">
            Screen and classify KALRO's advisory content, certify it onto the KilimoSTACK network, and
            put it to work behind a grounded, safety-aware AI advisory assistant — with room for other
            providers (input suppliers, FPOs, financial services) to join the same network.
          </p>
          <div className="mt-8 flex items-center gap-3">
            <Link to="/register" className="btn-primary text-base">
              Get started <ArrowRight className="h-4 w-4" />
            </Link>
            <Link to="/login" className="btn-secondary text-base">
              I already have an account
            </Link>
          </div>
        </div>
      </section>

      <section className="border-t border-wire bg-paper/50 px-6 py-16">
        <div className="mx-auto grid max-w-6xl gap-8 sm:grid-cols-3">
          <Feature
            icon={ShieldCheck}
            title="Screen & Classify"
            description="Check scientific accuracy and currency, then certify each item before it reaches a farmer — the same workflow whether it's a KALRO factsheet or a partner's equipment listing."
          />
          <Feature
            icon={Layers}
            title="Multi-provider network"
            description="Each institution — research bodies, FPOs, credit providers, input suppliers — manages its own certified catalog, discoverable network-wide via a shared Beckn-style layer."
          />
          <Feature
            icon={MessageCircleQuestion}
            title="Grounded AI advisory"
            description="Every answer is retrieved from certified content and generated by a self-hosted model — high-risk topics carry an explicit escalation notice, never a confident guess."
          />
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-16">
        <div className="card flex items-center justify-between gap-6 p-8">
          <div className="flex items-center gap-3">
            <Sprout className="h-6 w-6 text-herbarium" />
            <div>
              <p className="font-display text-xl font-semibold text-ink">Ready to screen your first resource?</p>
              <p className="mt-1 text-sm text-ink/55">Registration is open; provider access is granted by an administrator.</p>
            </div>
          </div>
          <Link to="/register" className="btn-primary flex-shrink-0">
            Create an account
          </Link>
        </div>
      </section>

      <footer className="border-t border-wire px-6 py-8 text-center text-xs text-ink/40">
        Reference client for the KALRO Provider Platform &amp; AI Layer — part of the KilimoSTACK / OpenAgriNet network.
      </footer>
    </div>
  );
}

function Feature({
  icon: Icon,
  title,
  description,
}: {
  icon: typeof ShieldCheck;
  title: string;
  description: string;
}) {
  return (
    <div>
      <div className="flex h-10 w-10 items-center justify-center rounded-[3px] bg-herbarium/10">
        <Icon className="h-5 w-5 text-herbarium" />
      </div>
      <h3 className="mt-3 font-display text-lg font-semibold text-ink">{title}</h3>
      <p className="mt-1.5 text-sm leading-relaxed text-ink/60">{description}</p>
    </div>
  );
}
